//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creature
    {
        public int CreatureID { get; set; }
        public string CreatureName { get; set; }
        public int ClassificationID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public int CSID { get; set; }
    
        public virtual Classification Classification { get; set; }
        public virtual CreatureStatus CreatureStatus { get; set; }
    }
}
